spring:
  datasource:
    name: Postgres PROD K8 Connection
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/k8_sample_db
    username: ${DB_USR}
    password: ${DB_PSW}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update # not recommended in production mode