apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgres-service-url: "postgres-service"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi