# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: binodleo/spring-pod:1.0
          imagePullPolicy: IfNotPresent # Change to IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_USR
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: psql-user
            - name: DB_PSW
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: psql-password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-service-url
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: web-app-config
                  key: active-profile
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  type: NodePort # Internal Service
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30036
#      nodePort: 30036 # Ensure this port is set
